# Setup & configure oh-my-zsh
export ZSH="$HOME/.oh-my-zsh"

# custom theme
ZSH_THEME="typewritten-sw"

# don't bother updating every two weeks
export UPDATE_ZSH_DAYS=60

ZSH_CUSTOM="$HOME/config/zsh/custom"
DISABLE_AUTO_TITLE="true"
COMPLETION_WAITING_DOTS="true"

plugins=(emoji git vi-mode vi-mode-cursor zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh


# Load nvm (only when called, to save boot time)
function nvm() {
  export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
  [ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"
  echo "nvm has been initialised! try again now!"
}

# Python
eval "$(pyenv init -)"

export VIRTUALENVWRAPPER_PYTHON=$(which python3)
source /Users/sam.whitehall/.pyenv/versions/3.6.15/bin/virtualenvwrapper.sh

# Flags for `less`
export LESS="IRS"


# Aliases
alias dcr=docker-compose run --rm
alias dcu=docker-compose up

alias vi=vim
alias vim=nvim

alias mdkir=mkdir

alias sz="source ~/.zshrc"
alias dt="python -c 'from datetime import datetime; print(datetime.utcnow().isoformat())'"

alias sandbox="cd ~/sandbox && pipenv run ipython"

# Load fzf (fuzzy-finder)
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND='ag -g ""'


# Global search and replace alias
function agr() {
    ag -l "$1" | xargs sed -i '' -e "s/$1/$2/g"
}
export PATH="/opt/homebrew/opt/openssl@3/bin:$PATH"

# Krakenflex
alias upside-login-development='eval $(upside-auth-login development)'
alias upside-login-prod

alias fixup='git commit -m "fixup w/last (dont merge)" --no-verify'

export PATH="$PATH:/Users/sam.whitehall/apps/ves/development/scripts/bin"

